name: Prod Build and Deploy

on:
  workflow_dispatch:
    inputs:
      deployment_phase:
        description: "Specify the deployment phase (e.g., patch, minor, major)"
        required: true
        default: "patch"

jobs:
  build-and-upload:
    runs-on: prod-runner-server
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.argocd_github_token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn     
        
      - name: Running Prod Deploy Script
        env:
          DEPLOYMENT_PHASE: ${{ github.event.inputs.deployment_phase }}
        run: |
          git config user.name "orbi-ci-bot"
          git config user.email "devops@eka.care"
          bash deploy-prod.sh ${DEPLOYMENT_PHASE}