name: Prod Revert Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Please enter Production tag in format : 0.0.0"
        default: ""
        required: true

jobs:
  build-and-upload:
    runs-on: prod-ec2-server-2
    steps:

      - name: Get the version
        id: get_version
        run: echo VERSION=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT

      - name: Checkout code to access git tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags

      - name: Check tag input and validate format
        env: 
          TAG: ${{ github.event.inputs.name }}
        run: |
           bash deploy-revert-prod.sh